version: '2'

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - certs:/erc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-proxy-le
    volumes_from:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro

  whoami1:
    image: jwilder/whoami
    expose:
      - "8000"
    environment:
      - VIRTUAL_HOST=test.lavstudcom.ru
      - VIRTUAL_PORT=8000
      - LETSENCRYPT_HOST=test.lavstudcom.ru
      - LETSENCRYPT_EMAIL=leontevannaivt@gmail.com

  whoami2:
    image: jwilder/whoami
    expose:
      - "8000"
    environment:
      - VIRTUAL_HOST=test.lavstudcom.ru
      - VIRTUAL_PORT=8000
      - LETSENRYPT_HOST=test.lavstudcom.ru
      - LETSENCRYPT_EMAIL=leontevannaivt@gmail.com

volumes:
  conf:
  vhost:
  html:
  dhparam:
  certs:
