-- MySQL Script generated by MySQL Workbench
-- Fri Jun 24 00:51:51 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema projectbd
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema projectbd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projectbd` DEFAULT CHARACTER SET utf8 ;
USE `projectbd` ;

-- -----------------------------------------------------
-- Table `projectbd`.` institutes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projectbd`.` institutes` (
  `id_institute` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(256) NOT NULL,
  `dean` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(14) NOT NULL,
  PRIMARY KEY (`id_institute`),
  UNIQUE INDEX `id institute_UNIQUE` (`id_institute` ASC) VISIBLE,
  UNIQUE INDEX `inst_name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `projectbd`.` repository`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projectbd`.` repository` (
  `id_repository` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `login` VARCHAR(45) NULL DEFAULT NULL,
  `password` VARCHAR(45) NULL DEFAULT NULL,
  `soft_key` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_repository`),
  UNIQUE INDEX `id repository_UNIQUE` (`id_repository` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `projectbd`.`departments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projectbd`.`departments` (
  `id_depart` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(256) NOT NULL,
  `inst_id` INT NOT NULL,
  `head_of_department` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(14) NOT NULL,
  PRIMARY KEY (`id_depart`),
  UNIQUE INDEX `id_depart_UNIQUE` (`id_depart` ASC) VISIBLE,
  INDEX `inst key_idx` (`inst_id` ASC) VISIBLE,
  CONSTRAINT `inst dep key`
    FOREIGN KEY (`inst_id`)
    REFERENCES `projectbd`.` institutes` (`id_institute`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `projectbd`.`classes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projectbd`.`classes` (
  `id_class` INT NOT NULL AUTO_INCREMENT,
  `num_class` VARCHAR(10) NOT NULL,
  `depart id` INT NOT NULL,
  PRIMARY KEY (`id_class`),
  INDEX `depart key_idx` (`depart id` ASC) VISIBLE,
  CONSTRAINT `depart class key`
    FOREIGN KEY (`depart id`)
    REFERENCES `projectbd`.`departments` (`id_depart`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `projectbd`.`computer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projectbd`.`computer` (
  `id_comp` INT NOT NULL AUTO_INCREMENT,
  `class_id` INT NULL DEFAULT NULL,
  `CPU` VARCHAR(100) NULL,
  `GPU` VARCHAR(100) NULL,
  `HDD/SSD` VARCHAR(100) NULL,
  `RAM` VARCHAR(100) NULL,
  `Motherboard` VARCHAR(100) NULL,
  PRIMARY KEY (`id_comp`),
  UNIQUE INDEX `id_comp_UNIQUE` (`id_comp` ASC) VISIBLE,
  INDEX `class key_idx` (`class_id` ASC) VISIBLE,
  CONSTRAINT `class comp key`
    FOREIGN KEY (`class_id`)
    REFERENCES `projectbd`.`classes` (`id_class`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `projectbd`.` repository_has_computer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projectbd`.` repository_has_computer` (
  `id_rep_comp` INT NOT NULL AUTO_INCREMENT,
  `repository_id_repository` INT NOT NULL,
  `computer_id_comp` INT NOT NULL,
  PRIMARY KEY (`id_rep_comp`),
  UNIQUE INDEX `id rep comp_UNIQUE` (`id_rep_comp` ASC) VISIBLE,
  INDEX `fk_ repository_has_computer_computer1_idx` (`computer_id_comp` ASC) VISIBLE,
  INDEX `fk_ repository_has_computer_ repository_idx` (`repository_id_repository` ASC) VISIBLE,
  CONSTRAINT `fk_ repository_has_computer_ repository`
    FOREIGN KEY (`repository_id_repository`)
    REFERENCES `projectbd`.` repository` (`id_repository`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ repository_has_computer_computer1`
    FOREIGN KEY (`computer_id_comp`)
    REFERENCES `projectbd`.`computer` (`id_comp`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `projectbd`.`profile of eng`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projectbd`.`profile of eng` (
  `id_profile` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(250) NOT NULL,
  `salary` INT NOT NULL,
  PRIMARY KEY (`id_profile`),
  UNIQUE INDEX `id profile_UNIQUE` (`id_profile` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `projectbd`.`engineers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projectbd`.`engineers` (
  `id_engineer` INT NOT NULL AUTO_INCREMENT,
  `profile_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `birthday` DATE NOT NULL,
  `sex` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id_engineer`),
  UNIQUE INDEX `id engineer_UNIQUE` (`id_engineer` ASC) VISIBLE,
  INDEX `profil eng_idx` (`profile_id` ASC) VISIBLE,
  CONSTRAINT `profil eng`
    FOREIGN KEY (`profile_id`)
    REFERENCES `projectbd`.`profile of eng` (`id_profile`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `projectbd`.`task`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projectbd`.`task` (
  `id_task` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `description` VARCHAR(250) NOT NULL,
  `deadline` DATE NULL,
  PRIMARY KEY (`id_task`),
  UNIQUE INDEX `id task_UNIQUE` (`id_task` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `projectbd`.`task_place`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projectbd`.`task_place` (
  `id_task_place` INT NOT NULL,
  `inst_id` INT NULL DEFAULT NULL,
  `departament_id` INT NULL DEFAULT NULL,
  `class_id` INT NULL DEFAULT NULL,
  `comp_id` INT NULL DEFAULT NULL,
  `task_id_task` INT NOT NULL,
  PRIMARY KEY (`id_task_place`),
  INDEX `fk_task place_task1_idx` (`task_id_task` ASC) VISIBLE,
  INDEX `inst key_idx` (`inst_id` ASC) VISIBLE,
  INDEX `depart key_idx` (`departament_id` ASC) VISIBLE,
  INDEX `class key_idx` (`class_id` ASC) VISIBLE,
  INDEX `comp key_idx` (`comp_id` ASC) VISIBLE,
  CONSTRAINT `class key`
    FOREIGN KEY (`class_id`)
    REFERENCES `projectbd`.`classes` (`id_class`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `comp key`
    FOREIGN KEY (`comp_id`)
    REFERENCES `projectbd`.`computer` (`id_comp`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `depart key`
    FOREIGN KEY (`departament_id`)
    REFERENCES `projectbd`.`departments` (`id_depart`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_task place_task1`
    FOREIGN KEY (`task_id_task`)
    REFERENCES `projectbd`.`task` (`id_task`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `inst key`
    FOREIGN KEY (`inst_id`)
    REFERENCES `projectbd`.` institutes` (`id_institute`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `projectbd`.`tasks_for_engineers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projectbd`.`tasks_for_engineers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `engineer id` INT NOT NULL,
  `task place_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `eng task key_idx` (`engineer id` ASC) VISIBLE,
  INDEX `task eng key_idx` (`task place_id` ASC) VISIBLE,
  CONSTRAINT `eng task key`
    FOREIGN KEY (`engineer id`)
    REFERENCES `projectbd`.`engineers` (`id_engineer`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `task eng key`
    FOREIGN KEY (`task place_id`)
    REFERENCES `projectbd`.`task_place` (`id_task_place`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

